version: '3.8'
services:

  minio:
    image: {{ minio_image }}:{{ minio_image_tag }}

    env_file:
      -  {{ minio_directory }}/env.minio

    volumes:
      -  {{ minio_data_directory }}:/data

    ports:
      - target: 9000
        published: 9002
        protocol: tcp
        mode: ingress

      - target: 9001
        published: 9001
        protocol: tcp
        mode: ingress

    command: server /data --console-address ":9001"

#            healthcheck:
#              test: curl -sS http://127.0.0.1 || echo 1
#              interval: 5s
#              timeout: 10s
#              retries: 3

    deploy:
        labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:{{ minio_domain }}"

    networks:
      - {{ public_network_name }}


#  minio-nginx:
#    image: {{ minio_nginx_image }}:{{ minio_nginx_image_tag }}
#    networks:
#      - {{ public_network_name }}
#    configs:
#      - source: minio_nginx_{{ minio_config_suffix }}
#        target: /etc/nginx/conf.d/default.conf
#    deploy:
#      labels:
#        - "traefik.enable=true"
#        - "traefik.port=80"
#        - "traefik.frontend.rule=Host:{{ minio_domain }}"


networks:
    {{ public_network_name }}:
        external: true

#configs:
#    minio_nginx_{{ minio_config_suffix }}:
#        external: true
